### ISSUE TITLE
Email is nil

### ISSUE THREAD

**Issue by jucdn** [ginjo/omniauth-slack#2]
Hi @ginjo 

Thanks again for the fork.

auth.info.email is nil for all of my users, but contains my email (I am the slack app admin). I don't know if this is an issue of the gem or the permission scopes of my app.

The permission scopes are : identity.avatar, identity.basic, **identity.email**, identity.team

**Comment by ginjo** [comment]
Hi @jucdn , thanks for helping me test!  :grinning:

I ran through the oauth cycle with a new token, given the permissions you specified, and I'm getting an email in the auth.info.email field. Here's part of the AuthHash object (minus sensitive data), just for comparison.

```yaml
--- !ruby/hash:OmniAuth::AuthHash
provider: slack
uid: U281GAVT5-T0BCJPFAM
info: !ruby/hash:OmniAuth::AuthHash::InfoHash
  name: Bill Richards
  email: myemail@gmail.com
  user_id: U281GAVT5
  team_name: WbrSandbox
  team_id: T0BCJPFAM
  image: https://secure.gravatar.com/avatar/.....png
  first_name: 
  last_name: 
  phone: 
  skype: 
  avatar_hash: 
  real_name: 
  real_name_normalized: 
  deleted: 
  status: 
  color: 
  tz: 
  tz_label: 
  tz_offset: 
  is_admin: 
  is_owner: 
  is_primary_owner: 
  is_restricted: 
  is_ultra_restricted: 
  is_bot: 
  has_2fa: 
  team_domain: wbrsandbox
  team_image: https://a.slack-edge.com/.....png
  team_email_domain: 
  nickname: Bill Richards
credentials: !ruby/hash:OmniAuth::AuthHash
  token: xoxp-1142.....
  expires: false
  scope: identity.basic,identity.email,identity.avatar,identity.team
extra: !ruby/hash:OmniAuth::AuthHash
  # more data here.
```

Your missing email data might have something to do with Slack permissions or settings. Here's the setup I'm working with. Look any different from yours?

* Using ginjo/omniauth-slack gem, features-and-fixes branch.
* An older "classic" Slack app with no restricted permissions.
* Classic Slack OAUTH2 API tokens, no "workspace tokens"
  (which aren't supported yet in omniauth-slack).
* One admin user, and one regular user (the one I ran the test on).
* Pretty much all settings in their default state.
* Before testing, I deleted the user's token from the team-app pairing,
  ensuring the scopes were the same as the ones you're using.

I would check the team (workspace) settings, the user settings, and the app settings & permissions for your app on that team, keeping an eye out for any kinds of restrictions.
